### PR TITLE
[ADD] iterations in decorator

### PR DESCRIPTION
**Pull request by johnashu**
When using horology, I often end up putting in a for loop for performace based timings over many iterations.

By adding it to the decorator, it can help for quick analysis.

If you are happy I can also look at adding the same functionality to the context manage.

I am unsure how this would fit with the `timed_iterable`, maybe conflicts, maybe not??

I will let you decide :)

### CODE REVIEW

**Comment by johnashu** [comment]
I added in functionality allowing users to set the decimal precision of the output..

Wrote Tests and Updated the Documentation.

**Comment by mjmikulski** [comment]
Hi! Thanks for commiting again :) I will have a look on the PR during the weekend. In the meantime, fix alerts from the LGTM bot.

**Comment by johnashu** [comment]
> Hi! Thanks for commiting again :) I will have a look on the PR during the weekend. In the meantime, fix alerts from the LGTM bot.

No problem... 
Its a great module and i use it daily.. 
It is nice to contribute and I am impressed by the standards you are setting!

I have updated the scope of the DP..

:)

**Comment by intermodaltelematics** [comment]
> **new alerts:**
> 
> * 1 for Unused local variable

Awkward... 

Should I reinit it in a new variable to remove this error?

`_dp = dp` ?

Or is it allowed?

**Comment by johnashu** [comment]
> 
> 
> > **new alerts:**
> > 
> > * 1 for Unused local variable
> 
> Awkward...
> 
> Should I reinit it in a new variable to remove this error?
> 
> `dp = dp` ?
> 
> Or is it allowed?

Sorry, I commented from work again lol.

Anyhow, The above? nothing? or this which is extra verbose  and should also alleviate the warnings from LGTM..:

`                if not isinstance(decimal_precision, int):
                    dp = 2
                else:
                    dp = decimal_precision`

**Comment by mjmikulski** [comment]
You suggest (correct me if I am wrong) creating a decorator that would act as [timeit](https://docs.python.org/3.8/library/timeit.html): it would repeat a call and return the average time (and probably some other statistics). For now it can be done with the Timed iterable, but not so conveniently.

So, it may be a good idea, but I would create a new decorator for it instead of adding a parameter in `@timed`.

Regarding decimal precision - it is a separate task and could be done as a separate PR. BTW, I prefer to think of significant figures, not number of digits after dot. 

Anyway, the code must make lgtm bot happy (i.e. no alerts) before being considered to be merged.

**Comment by intermodaltelematics** [comment]
> You suggest (correct me if I am wrong) creating a decorator that would act as [timeit](https://docs.python.org/3.8/library/timeit.html): it would repeat a call and return the average time (and probably some other statistics). For now it can be done with the Timed iterable, but not so conveniently.
> 
> So, it may be a good idea, but I would create a new decorator for it instead of adding a parameter in `@timed`.
> 
> Regarding decimal precision - it is a separate task and could be done as a separate PR. BTW, I prefer to think of significant figures, not number of digits after dot.
> 
> Anyway, the code must make lgtm bot happy (i.e. no alerts) before being considered to be merged.

I have split the 2 into different branches.

1 for decimal prescision.
2 for iterations.

The timed iterable times per item whereas the iterations would perform the same operation x times.

Yes! it is basically like timeit in my thinking..

Regarding significant numbers vs decimal prescision.  These are seperate things and maybe could incorporate both for different purposes.

Anyhow.. I will create a new PR regardling `digits` and we can discuss iterations here.

**Pull request closed without merging**
